theme: jekyll-theme-slate
title: Meghavarshini Krishnaswamy (Megh)
description: PhD Scholar at University of Arizona, Department of Linguistics
show_downloads: true
github:
#   zip_url: https://github.com/meghavarshini/meghavarshini.github.io/blob/master/resume/MeghavarshiniK_CV.pdf
  zip_url: /resume/MeghavarshiniK_CV.pdf
    

